name: Release

on:
  workflow_run:
    workflows: [ Test ]
    branches: [ main ]
    types: 
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Prepare to build
        run: go mod download

      - name: Delete Old Release
        uses: actions/github-script@v3
        with:
          script: |
            let release
            try {
              release = await github.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: 'v1.0'
              })
            } catch(e) {
              console.error(e)
              return
            }

            await github.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id
            })

            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/v1.0'
            })

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(TZ=CST date +'%Y-%m-%d')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          release_name: ${{ steps.date.outputs.date }}
          body: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      - name: Build
        run: |
          go build -ldflags "-s -w" -o feh ./cmd
          go build -ldflags "-s -w" -o run ./actions

      - name: Upload feh
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./feh
          asset_name: feh
          asset_content_type: application/octet-stream

      - name: Upload run
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./run
          asset_name: run
          asset_content_type: application/octet-stream
